package com.bookStore.Domain;
// Generated 2017-5-26 21:04:32 by Hibernate Tools 5.2.0.CR1

/**
 * Indent generated by hbm2java
 */
public class Indent implements java.io.Serializable {

	private static final long serialVersionUID = -8357151432725193340L;
	private String orderid;
	private Products users;
	private int uid;
	private int pid;
	private int allnumber;
	private double allvalue;
	private String address;

	public Indent() {
	}

	public Indent(String orderid, Products users, int uid, int pid, int allnumber, double allvalue, String address) {
		this.orderid = orderid;
		this.users = users;
		this.uid = uid;
		this.pid = pid;
		this.allnumber = allnumber;
		this.allvalue = allvalue;
		this.address = address;
	}

	public String getOrderid() {
		return this.orderid;
	}

	public void setOrderid(String orderid) {
		this.orderid = orderid;
	}

	public Products getUsers() {
		return this.users;
	}

	public void setUsers(Products users) {
		this.users = users;
	}

	public int getUid() {
		return this.uid;
	}

	public void setUid(int uid) {
		this.uid = uid;
	}

	public int getPid() {
		return this.pid;
	}

	public void setPid(int pid) {
		this.pid = pid;
	}

	public int getAllnumber() {
		return this.allnumber;
	}

	public void setAllnumber(int allnumber) {
		this.allnumber = allnumber;
	}

	public double getAllvalue() {
		return this.allvalue;
	}

	public void setAllvalue(double allvalue) {
		this.allvalue = allvalue;
	}

	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

}
