package com.bookStore.Domain;
// Generated 2017-5-26 21:04:32 by Hibernate Tools 5.2.0.CR1

/**
 * Sort generated by hbm2java
 */
public class Sort implements java.io.Serializable {

	private static final long serialVersionUID = 9090114708505125055L;
	private Integer id;
	private String sname;
	private Products products;

	public Sort() {
	}

	public Sort(String sname) {
		this.sname = sname;
	}

	public Sort(String sname, Products products) {
		this.sname = sname;
		this.products = products;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSname() {
		return this.sname;
	}

	public void setSname(String sname) {
		this.sname = sname;
	}

	public Products getProducts() {
		return this.products;
	}

	public void setProducts(Products products) {
		this.products = products;
	}

}
