package com.bookStore.Domain;
// Generated 2017-5-26 21:04:32 by Hibernate Tools 5.2.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users implements java.io.Serializable {

	private static final long serialVersionUID = -4362831780221644398L;
	private Integer id;
	private String eamil;
	private String name;
	private String password;
	private String gender;
	private String phone;
	private String introdction;
	private Set indents = new HashSet(0);

	public Users() {
	}

	public Users(String eamil, String name, String password, String gender, String phone, String introdction) {
		this.eamil = eamil;
		this.name = name;
		this.password = password;
		this.gender = gender;
		this.phone = phone;
		this.introdction = introdction;
	}

	public Users(String eamil, String name, String password, String gender, String phone, String introdction,
			Set indents) {
		this.eamil = eamil;
		this.name = name;
		this.password = password;
		this.gender = gender;
		this.phone = phone;
		this.introdction = introdction;
		this.indents = indents;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getEamil() {
		return this.eamil;
	}

	public void setEamil(String eamil) {
		this.eamil = eamil;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getIntrodction() {
		return this.introdction;
	}

	public void setIntrodction(String introdction) {
		this.introdction = introdction;
	}

	public Set getIndents() {
		return this.indents;
	}

	public void setIndents(Set indents) {
		this.indents = indents;
	}

}
